name: sheriff
on:
  push:
    branches:
      - master

jobs:
  sheriff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: install deps
        run: npm install

      - name: run tests
        run: npm test
