name: sheriff
on:
  push:
    branches:
      - master

jobs:
  sheriff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: npm
          cache-dependecy-path: ./package-lock.json

      - name: install deps
        run: npm install

      - name: run tests
        run: npm test
